name: React CI/CD

on:
  push:
    branches: [ production ]
#   pull_request:
#     branches: [ main ]
jobs:
  build:

    runs-on: plantsat_web_prod

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build --if-present
      env:
        CI: false
#writing this comment just for commit
